/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui.dialogs;

import gui.Project;

/**
 *
 * @author Eros Zanchetta <eros@sslmit.unibo.it>
 */
public class ProxyAuthDialog extends javax.swing.JDialog {

    private Project project;

    public void setProject(Project project) {
        this.project = project;
    }
    
    /**
     * Creates new form ProxyAuthentication
     */
    public ProxyAuthDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HttpProxyLabel = new javax.swing.JLabel();
        httpProxyUserTextField = new javax.swing.JTextField();
        httpUserLabel = new javax.swing.JLabel();
        httpPasswdLabel = new javax.swing.JLabel();
        httpProxyPWDPasswordField = new javax.swing.JPasswordField();
        HttpsProxyLabel = new javax.swing.JLabel();
        httpsProxyUserTextField = new javax.swing.JTextField();
        httpsUserLabel = new javax.swing.JLabel();
        httpsPasswdLabel = new javax.swing.JLabel();
        httpsProxyPWDPasswordField = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JButton();
        useSameCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Proxy Authentication Parameters");

        HttpProxyLabel.setText("HTTP Proxy");

        httpUserLabel.setText("Username");

        httpPasswdLabel.setText("Password");

        HttpsProxyLabel.setText("HTTPS Proxy");

        httpsUserLabel.setText("Username");

        httpsPasswdLabel.setText("Password");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        useSameCheckBox.setText("Use same settings for HTTP and HTTPS");
        useSameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useSameCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useSameCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(httpUserLabel)
                            .addComponent(HttpProxyLabel)
                            .addComponent(httpPasswdLabel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(httpProxyUserTextField)
                            .addComponent(httpProxyPWDPasswordField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(httpsUserLabel)
                            .addComponent(HttpsProxyLabel)
                            .addComponent(httpsPasswdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(httpsProxyUserTextField)
                            .addComponent(httpsProxyPWDPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useSameCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HttpProxyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpUserLabel)
                    .addComponent(httpProxyUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpPasswdLabel)
                    .addComponent(httpProxyPWDPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(HttpsProxyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpsUserLabel)
                    .addComponent(httpsProxyUserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(httpsPasswdLabel)
                    .addComponent(httpsProxyPWDPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        save();
        setVisible(false);
		dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void useSameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useSameCheckBoxActionPerformed
        toggleUseSameSettings();
    }//GEN-LAST:event_useSameCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProxyAuthDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProxyAuthDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProxyAuthDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProxyAuthDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProxyAuthDialog dialog = new ProxyAuthDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void toggleUseSameSettings() {
        HttpsProxyLabel.setEnabled(!useSameCheckBox.isSelected());
        httpsUserLabel.setEnabled(!useSameCheckBox.isSelected());
        httpsProxyUserTextField.setEnabled(!useSameCheckBox.isSelected());
        httpsPasswdLabel.setEnabled(!useSameCheckBox.isSelected());
        httpsProxyPWDPasswordField.setEnabled(!useSameCheckBox.isSelected());
        
        if (useSameCheckBox.isSelected()) {
            HttpProxyLabel.setText("HTTP(s) Proxy");
        }
        else {
            HttpProxyLabel.setText("HTTP Proxy");
        }
    }
    
    public void save() {
        
        if (useSameCheckBox.isSelected()) {
            project.setHttpProxyUser(httpProxyUserTextField.getText());
            project.setHttpsProxyUser(httpProxyUserTextField.getText());
            project.setHttpProxyPassword(String.valueOf(httpProxyPWDPasswordField.getPassword()));
            project.setHttpsProxyPassword(String.valueOf(httpProxyPWDPasswordField.getPassword()));
        }
        else {
            project.setHttpProxyUser(httpProxyUserTextField.getText());
            project.setHttpsProxyUser(httpsProxyUserTextField.getText());
            project.setHttpProxyPassword(String.valueOf(httpProxyPWDPasswordField.getPassword()));
            project.setHttpsProxyPassword(String.valueOf(httpsProxyPWDPasswordField.getPassword()));            
        }
        

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HttpProxyLabel;
    private javax.swing.JLabel HttpsProxyLabel;
    private javax.swing.JLabel httpPasswdLabel;
    private javax.swing.JPasswordField httpProxyPWDPasswordField;
    private javax.swing.JTextField httpProxyUserTextField;
    private javax.swing.JLabel httpUserLabel;
    private javax.swing.JLabel httpsPasswdLabel;
    private javax.swing.JPasswordField httpsProxyPWDPasswordField;
    private javax.swing.JTextField httpsProxyUserTextField;
    private javax.swing.JLabel httpsUserLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox useSameCheckBox;
    // End of variables declaration//GEN-END:variables
}
